[package]
name = "example-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.sonar]
organization = "marcelomiyake"
project-key = "marcelomiyake_microservices-template_example-service"
inclusions = ["**/*.rs"]
exclusions = ["target/**"]

[dependencies]
axum.workspace = true
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
