sonar.projectKey=microservices-template-web-api
sonar.projectName=Microservices Template Web API
sonar.sources=services/web-api/src
sonar.tests=services/web-api/tests
sonar.test.inclusions=services/web-api/tests/**/*.rs
sonar.coverage.exclusions=services/web-api/src/main.rs
sonar.rust.cargo.manifestPaths=services/web-api/Cargo.toml
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=target/coverage/web-api-clippy.json
sonar.rust.lcov.reportPaths=target/coverage/web-api.lcov
sonar.exclusions=**/target/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
