sonar.projectKey=microservices-template-web
sonar.projectName=Microservices Template Vue Frontend
sonar.sources=web/src/App.vue,web/src/main.ts,web/src/style.css
sonar.tests=web/src/App.spec.ts,web/e2e
sonar.test.inclusions=web/e2e/**/*.spec.ts,web/src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/test-results/**,**/playwright-report/**
sonar.sourceEncoding=UTF-8
