exampleService:
  image:
    repository: example-service
    tag: local
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi

webApi:
  image:
    repository: web-api
    tag: local
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi

web:
  image:
    repository: microservices-poc-web
    tag: local
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi
